#if !defined DESALT_PP_TUPLE_REM_IF_PAREN_HPP_INCLUDED_
#define      DESALT_PP_TUPLE_REM_IF_PAREN_HPP_INCLUDED_

#define DESALT_PP_TUPLE_REM_IF_PAREN(tup) \
    BOOST_PP_IIF(DESALT_PP_STARTS_WITH

#endif
