#if !defined DESALT_PP_STARTS_WITH_ENCLOSING_PAREN_HPP_INCLUDED_
#define      DESALT_PP_STARTS_WITH_ENCLOSING_PAREN_HPP_INCLUDED_

#include <desalt/preprocessor/cat.hpp>

#define DESALT_PP_STARTS_WITH_ENCLOSING_PAREN(...) \
    DESALT_PP_STARTS_WITH_ENCLOSING_PAREN_II( \
        DESALT_PP_CAT(DESALT_PP_STARTS_WITH_ENCLOSING_PAREN_HELPER_, \
                      DESALT_PP_STARTS_WITH_ENCLOSING_PAREN_I __VA_ARGS__))
#define DESALT_PP_STARTS_WITH_ENCLOSING_PAREN_I(...) OK
#define DESALT_PP_STARTS_WITH_ENCLOSING_PAREN_HELPER_OK 1,
#define DESALT_PP_STARTS_WITH_ENCLOSING_PAREN_HELPER_DESALT_PP_STARTS_WITH_ENCLOSING_PAREN_I 0,
#define DESALT_PP_STARTS_WITH_ENCLOSING_PAREN_II(...) \
    DESALT_PP_STARTS_WITH_ENCLOSING_PAREN_III(__VA_ARGS__)
#define DESALT_PP_STARTS_WITH_ENCLOSING_PAREN_III(x, ...) \
    x
#endif
