#if !defined DESALT_PP_WHILE_HPP_INCLUDED_
#define      DESALT_PP_WHILE_HPP_INCLUDED_

#include <boost/preprocessor/cat.hpp>
#include <boost/preprocessor/control/if.hpp>
#include <boost/preprocessor/tuple/eat.hpp>
#include <boost/preprocessor/detail/auto_rec.hpp>

#define DESALT_PP_WHILE BOOST_PP_CAT(DESALT_PP_WHILE_, BOOST_PP_AUTO_REC(DESALT_PP_WHILE_P, 8))

#define DESALT_PP_WHILE_P(n) BOOST_PP_CAT(DESALT_PP_WHILE_CHECK_, DESALT_PP_WHILE_ ## n(DESALT_PP_WHILE_HELPER_P, ~, DESALT_PP_WHILE_OK))
#define DESALT_PP_WHILE_CHECK_DESALT_PP_WHILE_OK 1
#define DESALT_PP_WHILE_CHECK_DESALT_PP_ERROR_WHILE_RECURSION_OVER 1
#define DESALT_PP_WHILE_CHECK_DESALT_PP_WHILE_1(p, op, st) 0
#define DESALT_PP_WHILE_CHECK_DESALT_PP_WHILE_2(p, op, st) 0
#define DESALT_PP_WHILE_CHECK_DESALT_PP_WHILE_3(p, op, st) 0
#define DESALT_PP_WHILE_CHECK_DESALT_PP_WHILE_4(p, op, st) 0
#define DESALT_PP_WHILE_CHECK_DESALT_PP_WHILE_5(p, op, st) 0
#define DESALT_PP_WHILE_CHECK_DESALT_PP_WHILE_6(p, op, st) 0
#define DESALT_PP_WHILE_CHECK_DESALT_PP_WHILE_7(p, op, st) 0
#define DESALT_PP_WHILE_CHECK_DESALT_PP_WHILE_8(p, op, st) 0

#define DESALT_PP_WHILE_HELPER_P(x, y) 0

#define DESALT_PP_WHILE_1(p, op, st) DESALT_PP_WHILE_1_I(p, BOOST_PP_IF(p(0, st), DESALT_PP_WHILE_1_15, st BOOST_PP_TUPLE_EAT(3))(p, op, st))
#define DESALT_PP_WHILE_1_I(p, st) BOOST_PP_IF(p(0, st), DESALT_PP_ERROR_WHILE_LOOP_OVER, st)

#define DESALT_PP_WHILE_1_15(p, op, st) DESALT_PP_WHILE_1_15_I(p, op, DESALT_PP_WHILE_1_14(p, op, st))
#define DESALT_PP_WHILE_1_15_I(p, op, st) DESALT_PP_WHILE_1_15_II(p, op, st)
#define DESALT_PP_WHILE_1_15_II(p, op, st) BOOST_PP_IF(p(0, st), DESALT_PP_WHILE_1_14, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_1_14(p, op, st) DESALT_PP_WHILE_1_14_I(p, op, DESALT_PP_WHILE_1_13(p, op, st))
#define DESALT_PP_WHILE_1_14_I(p, op, st) DESALT_PP_WHILE_1_14_II(p, op, st)
#define DESALT_PP_WHILE_1_14_II(p, op, st) BOOST_PP_IF(p(0, st), DESALT_PP_WHILE_1_13, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_1_13(p, op, st) DESALT_PP_WHILE_1_13_I(p, op, DESALT_PP_WHILE_1_12(p, op, st))
#define DESALT_PP_WHILE_1_13_I(p, op, st) DESALT_PP_WHILE_1_13_II(p, op, st)
#define DESALT_PP_WHILE_1_13_II(p, op, st) BOOST_PP_IF(p(0, st), DESALT_PP_WHILE_1_12, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_1_12(p, op, st) DESALT_PP_WHILE_1_12_I(p, op, DESALT_PP_WHILE_1_11(p, op, st))
#define DESALT_PP_WHILE_1_12_I(p, op, st) DESALT_PP_WHILE_1_12_II(p, op, st)
#define DESALT_PP_WHILE_1_12_II(p, op, st) BOOST_PP_IF(p(0, st), DESALT_PP_WHILE_1_11, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_1_11(p, op, st) DESALT_PP_WHILE_1_11_I(p, op, DESALT_PP_WHILE_1_10(p, op, st))
#define DESALT_PP_WHILE_1_11_I(p, op, st) DESALT_PP_WHILE_1_11_II(p, op, st)
#define DESALT_PP_WHILE_1_11_II(p, op, st) BOOST_PP_IF(p(0, st), DESALT_PP_WHILE_1_10, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_1_10(p, op, st) DESALT_PP_WHILE_1_10_I(p, op, DESALT_PP_WHILE_1_9(p, op, st))
#define DESALT_PP_WHILE_1_10_I(p, op, st) DESALT_PP_WHILE_1_10_II(p, op, st)
#define DESALT_PP_WHILE_1_10_II(p, op, st) BOOST_PP_IF(p(0, st), DESALT_PP_WHILE_1_9, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_1_9(p, op, st) DESALT_PP_WHILE_1_9_I(p, op, DESALT_PP_WHILE_1_8(p, op, st))
#define DESALT_PP_WHILE_1_9_I(p, op, st) DESALT_PP_WHILE_1_9_II(p, op, st)
#define DESALT_PP_WHILE_1_9_II(p, op, st) BOOST_PP_IF(p(0, st), DESALT_PP_WHILE_1_8, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_1_8(p, op, st) DESALT_PP_WHILE_1_8_I(p, op, DESALT_PP_WHILE_1_7(p, op, st))
#define DESALT_PP_WHILE_1_8_I(p, op, st) DESALT_PP_WHILE_1_8_II(p, op, st)
#define DESALT_PP_WHILE_1_8_II(p, op, st) BOOST_PP_IF(p(0, st), DESALT_PP_WHILE_1_7, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_1_7(p, op, st) DESALT_PP_WHILE_1_7_I(p, op, DESALT_PP_WHILE_1_6(p, op, st))
#define DESALT_PP_WHILE_1_7_I(p, op, st) DESALT_PP_WHILE_1_7_II(p, op, st)
#define DESALT_PP_WHILE_1_7_II(p, op, st) BOOST_PP_IF(p(0, st), DESALT_PP_WHILE_1_6, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_1_6(p, op, st) DESALT_PP_WHILE_1_6_I(p, op, DESALT_PP_WHILE_1_5(p, op, st))
#define DESALT_PP_WHILE_1_6_I(p, op, st) DESALT_PP_WHILE_1_6_II(p, op, st)
#define DESALT_PP_WHILE_1_6_II(p, op, st) BOOST_PP_IF(p(0, st), DESALT_PP_WHILE_1_5, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_1_5(p, op, st) DESALT_PP_WHILE_1_5_I(p, op, DESALT_PP_WHILE_1_4(p, op, st))
#define DESALT_PP_WHILE_1_5_I(p, op, st) DESALT_PP_WHILE_1_5_II(p, op, st)
#define DESALT_PP_WHILE_1_5_II(p, op, st) BOOST_PP_IF(p(0, st), DESALT_PP_WHILE_1_4, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_1_4(p, op, st) DESALT_PP_WHILE_1_4_I(p, op, DESALT_PP_WHILE_1_3(p, op, st))
#define DESALT_PP_WHILE_1_4_I(p, op, st) DESALT_PP_WHILE_1_4_II(p, op, st)
#define DESALT_PP_WHILE_1_4_II(p, op, st) BOOST_PP_IF(p(0, st), DESALT_PP_WHILE_1_3, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_1_3(p, op, st) DESALT_PP_WHILE_1_3_I(p, op, DESALT_PP_WHILE_1_2(p, op, st))
#define DESALT_PP_WHILE_1_3_I(p, op, st) DESALT_PP_WHILE_1_3_II(p, op, st)
#define DESALT_PP_WHILE_1_3_II(p, op, st) BOOST_PP_IF(p(0, st), DESALT_PP_WHILE_1_2, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_1_2(p, op, st) DESALT_PP_WHILE_1_2_I(p, op, DESALT_PP_WHILE_1_1(p, op, st))
#define DESALT_PP_WHILE_1_2_I(p, op, st) DESALT_PP_WHILE_1_2_II(p, op, st)
#define DESALT_PP_WHILE_1_2_II(p, op, st) BOOST_PP_IF(p(0, st), DESALT_PP_WHILE_1_1, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_1_1(p, op, st) DESALT_PP_WHILE_1_1_I(p, op, DESALT_PP_WHILE_1_0(p, op, st))
#define DESALT_PP_WHILE_1_1_I(p, op, st) DESALT_PP_WHILE_1_1_II(p, op, st)
#define DESALT_PP_WHILE_1_1_II(p, op, st) BOOST_PP_IF(p(0, st), DESALT_PP_WHILE_1_0, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_1_0(p, op, st) op(0, st)

#define DESALT_PP_WHILE_2(p, op, st) DESALT_PP_WHILE_2_I(p, BOOST_PP_IF(p(1, st), DESALT_PP_WHILE_2_15, st BOOST_PP_TUPLE_EAT(3))(p, op, st))
#define DESALT_PP_WHILE_2_I(p, st) BOOST_PP_IF(p(1, st), DESALT_PP_ERROR_WHILE_LOOP_OVER, st)

#define DESALT_PP_WHILE_2_15(p, op, st) DESALT_PP_WHILE_2_15_I(p, op, DESALT_PP_WHILE_2_14(p, op, st))
#define DESALT_PP_WHILE_2_15_I(p, op, st) DESALT_PP_WHILE_2_15_II(p, op, st)
#define DESALT_PP_WHILE_2_15_II(p, op, st) BOOST_PP_IF(p(1, st), DESALT_PP_WHILE_2_14, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_2_14(p, op, st) DESALT_PP_WHILE_2_14_I(p, op, DESALT_PP_WHILE_2_13(p, op, st))
#define DESALT_PP_WHILE_2_14_I(p, op, st) DESALT_PP_WHILE_2_14_II(p, op, st)
#define DESALT_PP_WHILE_2_14_II(p, op, st) BOOST_PP_IF(p(1, st), DESALT_PP_WHILE_2_13, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_2_13(p, op, st) DESALT_PP_WHILE_2_13_I(p, op, DESALT_PP_WHILE_2_12(p, op, st))
#define DESALT_PP_WHILE_2_13_I(p, op, st) DESALT_PP_WHILE_2_13_II(p, op, st)
#define DESALT_PP_WHILE_2_13_II(p, op, st) BOOST_PP_IF(p(1, st), DESALT_PP_WHILE_2_12, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_2_12(p, op, st) DESALT_PP_WHILE_2_12_I(p, op, DESALT_PP_WHILE_2_11(p, op, st))
#define DESALT_PP_WHILE_2_12_I(p, op, st) DESALT_PP_WHILE_2_12_II(p, op, st)
#define DESALT_PP_WHILE_2_12_II(p, op, st) BOOST_PP_IF(p(1, st), DESALT_PP_WHILE_2_11, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_2_11(p, op, st) DESALT_PP_WHILE_2_11_I(p, op, DESALT_PP_WHILE_2_10(p, op, st))
#define DESALT_PP_WHILE_2_11_I(p, op, st) DESALT_PP_WHILE_2_11_II(p, op, st)
#define DESALT_PP_WHILE_2_11_II(p, op, st) BOOST_PP_IF(p(1, st), DESALT_PP_WHILE_2_10, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_2_10(p, op, st) DESALT_PP_WHILE_2_10_I(p, op, DESALT_PP_WHILE_2_9(p, op, st))
#define DESALT_PP_WHILE_2_10_I(p, op, st) DESALT_PP_WHILE_2_10_II(p, op, st)
#define DESALT_PP_WHILE_2_10_II(p, op, st) BOOST_PP_IF(p(1, st), DESALT_PP_WHILE_2_9, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_2_9(p, op, st) DESALT_PP_WHILE_2_9_I(p, op, DESALT_PP_WHILE_2_8(p, op, st))
#define DESALT_PP_WHILE_2_9_I(p, op, st) DESALT_PP_WHILE_2_9_II(p, op, st)
#define DESALT_PP_WHILE_2_9_II(p, op, st) BOOST_PP_IF(p(1, st), DESALT_PP_WHILE_2_8, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_2_8(p, op, st) DESALT_PP_WHILE_2_8_I(p, op, DESALT_PP_WHILE_2_7(p, op, st))
#define DESALT_PP_WHILE_2_8_I(p, op, st) DESALT_PP_WHILE_2_8_II(p, op, st)
#define DESALT_PP_WHILE_2_8_II(p, op, st) BOOST_PP_IF(p(1, st), DESALT_PP_WHILE_2_7, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_2_7(p, op, st) DESALT_PP_WHILE_2_7_I(p, op, DESALT_PP_WHILE_2_6(p, op, st))
#define DESALT_PP_WHILE_2_7_I(p, op, st) DESALT_PP_WHILE_2_7_II(p, op, st)
#define DESALT_PP_WHILE_2_7_II(p, op, st) BOOST_PP_IF(p(1, st), DESALT_PP_WHILE_2_6, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_2_6(p, op, st) DESALT_PP_WHILE_2_6_I(p, op, DESALT_PP_WHILE_2_5(p, op, st))
#define DESALT_PP_WHILE_2_6_I(p, op, st) DESALT_PP_WHILE_2_6_II(p, op, st)
#define DESALT_PP_WHILE_2_6_II(p, op, st) BOOST_PP_IF(p(1, st), DESALT_PP_WHILE_2_5, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_2_5(p, op, st) DESALT_PP_WHILE_2_5_I(p, op, DESALT_PP_WHILE_2_4(p, op, st))
#define DESALT_PP_WHILE_2_5_I(p, op, st) DESALT_PP_WHILE_2_5_II(p, op, st)
#define DESALT_PP_WHILE_2_5_II(p, op, st) BOOST_PP_IF(p(1, st), DESALT_PP_WHILE_2_4, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_2_4(p, op, st) DESALT_PP_WHILE_2_4_I(p, op, DESALT_PP_WHILE_2_3(p, op, st))
#define DESALT_PP_WHILE_2_4_I(p, op, st) DESALT_PP_WHILE_2_4_II(p, op, st)
#define DESALT_PP_WHILE_2_4_II(p, op, st) BOOST_PP_IF(p(1, st), DESALT_PP_WHILE_2_3, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_2_3(p, op, st) DESALT_PP_WHILE_2_3_I(p, op, DESALT_PP_WHILE_2_2(p, op, st))
#define DESALT_PP_WHILE_2_3_I(p, op, st) DESALT_PP_WHILE_2_3_II(p, op, st)
#define DESALT_PP_WHILE_2_3_II(p, op, st) BOOST_PP_IF(p(1, st), DESALT_PP_WHILE_2_2, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_2_2(p, op, st) DESALT_PP_WHILE_2_2_I(p, op, DESALT_PP_WHILE_2_1(p, op, st))
#define DESALT_PP_WHILE_2_2_I(p, op, st) DESALT_PP_WHILE_2_2_II(p, op, st)
#define DESALT_PP_WHILE_2_2_II(p, op, st) BOOST_PP_IF(p(1, st), DESALT_PP_WHILE_2_1, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_2_1(p, op, st) DESALT_PP_WHILE_2_1_I(p, op, DESALT_PP_WHILE_2_0(p, op, st))
#define DESALT_PP_WHILE_2_1_I(p, op, st) DESALT_PP_WHILE_2_1_II(p, op, st)
#define DESALT_PP_WHILE_2_1_II(p, op, st) BOOST_PP_IF(p(1, st), DESALT_PP_WHILE_2_0, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_2_0(p, op, st) op(1, st)

#define DESALT_PP_WHILE_3(p, op, st) DESALT_PP_WHILE_3_I(p, BOOST_PP_IF(p(2, st), DESALT_PP_WHILE_3_15, st BOOST_PP_TUPLE_EAT(3))(p, op, st))
#define DESALT_PP_WHILE_3_I(p, st) BOOST_PP_IF(p(2, st), DESALT_PP_ERROR_WHILE_LOOP_OVER, st)

#define DESALT_PP_WHILE_3_15(p, op, st) DESALT_PP_WHILE_3_15_I(p, op, DESALT_PP_WHILE_3_14(p, op, st))
#define DESALT_PP_WHILE_3_15_I(p, op, st) DESALT_PP_WHILE_3_15_II(p, op, st)
#define DESALT_PP_WHILE_3_15_II(p, op, st) BOOST_PP_IF(p(2, st), DESALT_PP_WHILE_3_14, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_3_14(p, op, st) DESALT_PP_WHILE_3_14_I(p, op, DESALT_PP_WHILE_3_13(p, op, st))
#define DESALT_PP_WHILE_3_14_I(p, op, st) DESALT_PP_WHILE_3_14_II(p, op, st)
#define DESALT_PP_WHILE_3_14_II(p, op, st) BOOST_PP_IF(p(2, st), DESALT_PP_WHILE_3_13, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_3_13(p, op, st) DESALT_PP_WHILE_3_13_I(p, op, DESALT_PP_WHILE_3_12(p, op, st))
#define DESALT_PP_WHILE_3_13_I(p, op, st) DESALT_PP_WHILE_3_13_II(p, op, st)
#define DESALT_PP_WHILE_3_13_II(p, op, st) BOOST_PP_IF(p(2, st), DESALT_PP_WHILE_3_12, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_3_12(p, op, st) DESALT_PP_WHILE_3_12_I(p, op, DESALT_PP_WHILE_3_11(p, op, st))
#define DESALT_PP_WHILE_3_12_I(p, op, st) DESALT_PP_WHILE_3_12_II(p, op, st)
#define DESALT_PP_WHILE_3_12_II(p, op, st) BOOST_PP_IF(p(2, st), DESALT_PP_WHILE_3_11, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_3_11(p, op, st) DESALT_PP_WHILE_3_11_I(p, op, DESALT_PP_WHILE_3_10(p, op, st))
#define DESALT_PP_WHILE_3_11_I(p, op, st) DESALT_PP_WHILE_3_11_II(p, op, st)
#define DESALT_PP_WHILE_3_11_II(p, op, st) BOOST_PP_IF(p(2, st), DESALT_PP_WHILE_3_10, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_3_10(p, op, st) DESALT_PP_WHILE_3_10_I(p, op, DESALT_PP_WHILE_3_9(p, op, st))
#define DESALT_PP_WHILE_3_10_I(p, op, st) DESALT_PP_WHILE_3_10_II(p, op, st)
#define DESALT_PP_WHILE_3_10_II(p, op, st) BOOST_PP_IF(p(2, st), DESALT_PP_WHILE_3_9, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_3_9(p, op, st) DESALT_PP_WHILE_3_9_I(p, op, DESALT_PP_WHILE_3_8(p, op, st))
#define DESALT_PP_WHILE_3_9_I(p, op, st) DESALT_PP_WHILE_3_9_II(p, op, st)
#define DESALT_PP_WHILE_3_9_II(p, op, st) BOOST_PP_IF(p(2, st), DESALT_PP_WHILE_3_8, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_3_8(p, op, st) DESALT_PP_WHILE_3_8_I(p, op, DESALT_PP_WHILE_3_7(p, op, st))
#define DESALT_PP_WHILE_3_8_I(p, op, st) DESALT_PP_WHILE_3_8_II(p, op, st)
#define DESALT_PP_WHILE_3_8_II(p, op, st) BOOST_PP_IF(p(2, st), DESALT_PP_WHILE_3_7, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_3_7(p, op, st) DESALT_PP_WHILE_3_7_I(p, op, DESALT_PP_WHILE_3_6(p, op, st))
#define DESALT_PP_WHILE_3_7_I(p, op, st) DESALT_PP_WHILE_3_7_II(p, op, st)
#define DESALT_PP_WHILE_3_7_II(p, op, st) BOOST_PP_IF(p(2, st), DESALT_PP_WHILE_3_6, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_3_6(p, op, st) DESALT_PP_WHILE_3_6_I(p, op, DESALT_PP_WHILE_3_5(p, op, st))
#define DESALT_PP_WHILE_3_6_I(p, op, st) DESALT_PP_WHILE_3_6_II(p, op, st)
#define DESALT_PP_WHILE_3_6_II(p, op, st) BOOST_PP_IF(p(2, st), DESALT_PP_WHILE_3_5, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_3_5(p, op, st) DESALT_PP_WHILE_3_5_I(p, op, DESALT_PP_WHILE_3_4(p, op, st))
#define DESALT_PP_WHILE_3_5_I(p, op, st) DESALT_PP_WHILE_3_5_II(p, op, st)
#define DESALT_PP_WHILE_3_5_II(p, op, st) BOOST_PP_IF(p(2, st), DESALT_PP_WHILE_3_4, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_3_4(p, op, st) DESALT_PP_WHILE_3_4_I(p, op, DESALT_PP_WHILE_3_3(p, op, st))
#define DESALT_PP_WHILE_3_4_I(p, op, st) DESALT_PP_WHILE_3_4_II(p, op, st)
#define DESALT_PP_WHILE_3_4_II(p, op, st) BOOST_PP_IF(p(2, st), DESALT_PP_WHILE_3_3, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_3_3(p, op, st) DESALT_PP_WHILE_3_3_I(p, op, DESALT_PP_WHILE_3_2(p, op, st))
#define DESALT_PP_WHILE_3_3_I(p, op, st) DESALT_PP_WHILE_3_3_II(p, op, st)
#define DESALT_PP_WHILE_3_3_II(p, op, st) BOOST_PP_IF(p(2, st), DESALT_PP_WHILE_3_2, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_3_2(p, op, st) DESALT_PP_WHILE_3_2_I(p, op, DESALT_PP_WHILE_3_1(p, op, st))
#define DESALT_PP_WHILE_3_2_I(p, op, st) DESALT_PP_WHILE_3_2_II(p, op, st)
#define DESALT_PP_WHILE_3_2_II(p, op, st) BOOST_PP_IF(p(2, st), DESALT_PP_WHILE_3_1, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_3_1(p, op, st) DESALT_PP_WHILE_3_1_I(p, op, DESALT_PP_WHILE_3_0(p, op, st))
#define DESALT_PP_WHILE_3_1_I(p, op, st) DESALT_PP_WHILE_3_1_II(p, op, st)
#define DESALT_PP_WHILE_3_1_II(p, op, st) BOOST_PP_IF(p(2, st), DESALT_PP_WHILE_3_0, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_3_0(p, op, st) op(2, st)

#define DESALT_PP_WHILE_4(p, op, st) DESALT_PP_WHILE_4_I(p, BOOST_PP_IF(p(3, st), DESALT_PP_WHILE_4_15, st BOOST_PP_TUPLE_EAT(3))(p, op, st))
#define DESALT_PP_WHILE_4_I(p, st) BOOST_PP_IF(p(3, st), DESALT_PP_ERROR_WHILE_LOOP_OVER, st)

#define DESALT_PP_WHILE_4_15(p, op, st) DESALT_PP_WHILE_4_15_I(p, op, DESALT_PP_WHILE_4_14(p, op, st))
#define DESALT_PP_WHILE_4_15_I(p, op, st) DESALT_PP_WHILE_4_15_II(p, op, st)
#define DESALT_PP_WHILE_4_15_II(p, op, st) BOOST_PP_IF(p(3, st), DESALT_PP_WHILE_4_14, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_4_14(p, op, st) DESALT_PP_WHILE_4_14_I(p, op, DESALT_PP_WHILE_4_13(p, op, st))
#define DESALT_PP_WHILE_4_14_I(p, op, st) DESALT_PP_WHILE_4_14_II(p, op, st)
#define DESALT_PP_WHILE_4_14_II(p, op, st) BOOST_PP_IF(p(3, st), DESALT_PP_WHILE_4_13, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_4_13(p, op, st) DESALT_PP_WHILE_4_13_I(p, op, DESALT_PP_WHILE_4_12(p, op, st))
#define DESALT_PP_WHILE_4_13_I(p, op, st) DESALT_PP_WHILE_4_13_II(p, op, st)
#define DESALT_PP_WHILE_4_13_II(p, op, st) BOOST_PP_IF(p(3, st), DESALT_PP_WHILE_4_12, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_4_12(p, op, st) DESALT_PP_WHILE_4_12_I(p, op, DESALT_PP_WHILE_4_11(p, op, st))
#define DESALT_PP_WHILE_4_12_I(p, op, st) DESALT_PP_WHILE_4_12_II(p, op, st)
#define DESALT_PP_WHILE_4_12_II(p, op, st) BOOST_PP_IF(p(3, st), DESALT_PP_WHILE_4_11, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_4_11(p, op, st) DESALT_PP_WHILE_4_11_I(p, op, DESALT_PP_WHILE_4_10(p, op, st))
#define DESALT_PP_WHILE_4_11_I(p, op, st) DESALT_PP_WHILE_4_11_II(p, op, st)
#define DESALT_PP_WHILE_4_11_II(p, op, st) BOOST_PP_IF(p(3, st), DESALT_PP_WHILE_4_10, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_4_10(p, op, st) DESALT_PP_WHILE_4_10_I(p, op, DESALT_PP_WHILE_4_9(p, op, st))
#define DESALT_PP_WHILE_4_10_I(p, op, st) DESALT_PP_WHILE_4_10_II(p, op, st)
#define DESALT_PP_WHILE_4_10_II(p, op, st) BOOST_PP_IF(p(3, st), DESALT_PP_WHILE_4_9, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_4_9(p, op, st) DESALT_PP_WHILE_4_9_I(p, op, DESALT_PP_WHILE_4_8(p, op, st))
#define DESALT_PP_WHILE_4_9_I(p, op, st) DESALT_PP_WHILE_4_9_II(p, op, st)
#define DESALT_PP_WHILE_4_9_II(p, op, st) BOOST_PP_IF(p(3, st), DESALT_PP_WHILE_4_8, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_4_8(p, op, st) DESALT_PP_WHILE_4_8_I(p, op, DESALT_PP_WHILE_4_7(p, op, st))
#define DESALT_PP_WHILE_4_8_I(p, op, st) DESALT_PP_WHILE_4_8_II(p, op, st)
#define DESALT_PP_WHILE_4_8_II(p, op, st) BOOST_PP_IF(p(3, st), DESALT_PP_WHILE_4_7, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_4_7(p, op, st) DESALT_PP_WHILE_4_7_I(p, op, DESALT_PP_WHILE_4_6(p, op, st))
#define DESALT_PP_WHILE_4_7_I(p, op, st) DESALT_PP_WHILE_4_7_II(p, op, st)
#define DESALT_PP_WHILE_4_7_II(p, op, st) BOOST_PP_IF(p(3, st), DESALT_PP_WHILE_4_6, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_4_6(p, op, st) DESALT_PP_WHILE_4_6_I(p, op, DESALT_PP_WHILE_4_5(p, op, st))
#define DESALT_PP_WHILE_4_6_I(p, op, st) DESALT_PP_WHILE_4_6_II(p, op, st)
#define DESALT_PP_WHILE_4_6_II(p, op, st) BOOST_PP_IF(p(3, st), DESALT_PP_WHILE_4_5, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_4_5(p, op, st) DESALT_PP_WHILE_4_5_I(p, op, DESALT_PP_WHILE_4_4(p, op, st))
#define DESALT_PP_WHILE_4_5_I(p, op, st) DESALT_PP_WHILE_4_5_II(p, op, st)
#define DESALT_PP_WHILE_4_5_II(p, op, st) BOOST_PP_IF(p(3, st), DESALT_PP_WHILE_4_4, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_4_4(p, op, st) DESALT_PP_WHILE_4_4_I(p, op, DESALT_PP_WHILE_4_3(p, op, st))
#define DESALT_PP_WHILE_4_4_I(p, op, st) DESALT_PP_WHILE_4_4_II(p, op, st)
#define DESALT_PP_WHILE_4_4_II(p, op, st) BOOST_PP_IF(p(3, st), DESALT_PP_WHILE_4_3, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_4_3(p, op, st) DESALT_PP_WHILE_4_3_I(p, op, DESALT_PP_WHILE_4_2(p, op, st))
#define DESALT_PP_WHILE_4_3_I(p, op, st) DESALT_PP_WHILE_4_3_II(p, op, st)
#define DESALT_PP_WHILE_4_3_II(p, op, st) BOOST_PP_IF(p(3, st), DESALT_PP_WHILE_4_2, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_4_2(p, op, st) DESALT_PP_WHILE_4_2_I(p, op, DESALT_PP_WHILE_4_1(p, op, st))
#define DESALT_PP_WHILE_4_2_I(p, op, st) DESALT_PP_WHILE_4_2_II(p, op, st)
#define DESALT_PP_WHILE_4_2_II(p, op, st) BOOST_PP_IF(p(3, st), DESALT_PP_WHILE_4_1, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_4_1(p, op, st) DESALT_PP_WHILE_4_1_I(p, op, DESALT_PP_WHILE_4_0(p, op, st))
#define DESALT_PP_WHILE_4_1_I(p, op, st) DESALT_PP_WHILE_4_1_II(p, op, st)
#define DESALT_PP_WHILE_4_1_II(p, op, st) BOOST_PP_IF(p(3, st), DESALT_PP_WHILE_4_0, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_4_0(p, op, st) op(3, st)

#define DESALT_PP_WHILE_5(p, op, st) DESALT_PP_WHILE_5_I(p, BOOST_PP_IF(p(4, st), DESALT_PP_WHILE_5_15, st BOOST_PP_TUPLE_EAT(3))(p, op, st))
#define DESALT_PP_WHILE_5_I(p, st) BOOST_PP_IF(p(4, st), DESALT_PP_ERROR_WHILE_LOOP_OVER, st)

#define DESALT_PP_WHILE_5_15(p, op, st) DESALT_PP_WHILE_5_15_I(p, op, DESALT_PP_WHILE_5_14(p, op, st))
#define DESALT_PP_WHILE_5_15_I(p, op, st) DESALT_PP_WHILE_5_15_II(p, op, st)
#define DESALT_PP_WHILE_5_15_II(p, op, st) BOOST_PP_IF(p(4, st), DESALT_PP_WHILE_5_14, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_5_14(p, op, st) DESALT_PP_WHILE_5_14_I(p, op, DESALT_PP_WHILE_5_13(p, op, st))
#define DESALT_PP_WHILE_5_14_I(p, op, st) DESALT_PP_WHILE_5_14_II(p, op, st)
#define DESALT_PP_WHILE_5_14_II(p, op, st) BOOST_PP_IF(p(4, st), DESALT_PP_WHILE_5_13, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_5_13(p, op, st) DESALT_PP_WHILE_5_13_I(p, op, DESALT_PP_WHILE_5_12(p, op, st))
#define DESALT_PP_WHILE_5_13_I(p, op, st) DESALT_PP_WHILE_5_13_II(p, op, st)
#define DESALT_PP_WHILE_5_13_II(p, op, st) BOOST_PP_IF(p(4, st), DESALT_PP_WHILE_5_12, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_5_12(p, op, st) DESALT_PP_WHILE_5_12_I(p, op, DESALT_PP_WHILE_5_11(p, op, st))
#define DESALT_PP_WHILE_5_12_I(p, op, st) DESALT_PP_WHILE_5_12_II(p, op, st)
#define DESALT_PP_WHILE_5_12_II(p, op, st) BOOST_PP_IF(p(4, st), DESALT_PP_WHILE_5_11, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_5_11(p, op, st) DESALT_PP_WHILE_5_11_I(p, op, DESALT_PP_WHILE_5_10(p, op, st))
#define DESALT_PP_WHILE_5_11_I(p, op, st) DESALT_PP_WHILE_5_11_II(p, op, st)
#define DESALT_PP_WHILE_5_11_II(p, op, st) BOOST_PP_IF(p(4, st), DESALT_PP_WHILE_5_10, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_5_10(p, op, st) DESALT_PP_WHILE_5_10_I(p, op, DESALT_PP_WHILE_5_9(p, op, st))
#define DESALT_PP_WHILE_5_10_I(p, op, st) DESALT_PP_WHILE_5_10_II(p, op, st)
#define DESALT_PP_WHILE_5_10_II(p, op, st) BOOST_PP_IF(p(4, st), DESALT_PP_WHILE_5_9, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_5_9(p, op, st) DESALT_PP_WHILE_5_9_I(p, op, DESALT_PP_WHILE_5_8(p, op, st))
#define DESALT_PP_WHILE_5_9_I(p, op, st) DESALT_PP_WHILE_5_9_II(p, op, st)
#define DESALT_PP_WHILE_5_9_II(p, op, st) BOOST_PP_IF(p(4, st), DESALT_PP_WHILE_5_8, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_5_8(p, op, st) DESALT_PP_WHILE_5_8_I(p, op, DESALT_PP_WHILE_5_7(p, op, st))
#define DESALT_PP_WHILE_5_8_I(p, op, st) DESALT_PP_WHILE_5_8_II(p, op, st)
#define DESALT_PP_WHILE_5_8_II(p, op, st) BOOST_PP_IF(p(4, st), DESALT_PP_WHILE_5_7, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_5_7(p, op, st) DESALT_PP_WHILE_5_7_I(p, op, DESALT_PP_WHILE_5_6(p, op, st))
#define DESALT_PP_WHILE_5_7_I(p, op, st) DESALT_PP_WHILE_5_7_II(p, op, st)
#define DESALT_PP_WHILE_5_7_II(p, op, st) BOOST_PP_IF(p(4, st), DESALT_PP_WHILE_5_6, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_5_6(p, op, st) DESALT_PP_WHILE_5_6_I(p, op, DESALT_PP_WHILE_5_5(p, op, st))
#define DESALT_PP_WHILE_5_6_I(p, op, st) DESALT_PP_WHILE_5_6_II(p, op, st)
#define DESALT_PP_WHILE_5_6_II(p, op, st) BOOST_PP_IF(p(4, st), DESALT_PP_WHILE_5_5, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_5_5(p, op, st) DESALT_PP_WHILE_5_5_I(p, op, DESALT_PP_WHILE_5_4(p, op, st))
#define DESALT_PP_WHILE_5_5_I(p, op, st) DESALT_PP_WHILE_5_5_II(p, op, st)
#define DESALT_PP_WHILE_5_5_II(p, op, st) BOOST_PP_IF(p(4, st), DESALT_PP_WHILE_5_4, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_5_4(p, op, st) DESALT_PP_WHILE_5_4_I(p, op, DESALT_PP_WHILE_5_3(p, op, st))
#define DESALT_PP_WHILE_5_4_I(p, op, st) DESALT_PP_WHILE_5_4_II(p, op, st)
#define DESALT_PP_WHILE_5_4_II(p, op, st) BOOST_PP_IF(p(4, st), DESALT_PP_WHILE_5_3, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_5_3(p, op, st) DESALT_PP_WHILE_5_3_I(p, op, DESALT_PP_WHILE_5_2(p, op, st))
#define DESALT_PP_WHILE_5_3_I(p, op, st) DESALT_PP_WHILE_5_3_II(p, op, st)
#define DESALT_PP_WHILE_5_3_II(p, op, st) BOOST_PP_IF(p(4, st), DESALT_PP_WHILE_5_2, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_5_2(p, op, st) DESALT_PP_WHILE_5_2_I(p, op, DESALT_PP_WHILE_5_1(p, op, st))
#define DESALT_PP_WHILE_5_2_I(p, op, st) DESALT_PP_WHILE_5_2_II(p, op, st)
#define DESALT_PP_WHILE_5_2_II(p, op, st) BOOST_PP_IF(p(4, st), DESALT_PP_WHILE_5_1, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_5_1(p, op, st) DESALT_PP_WHILE_5_1_I(p, op, DESALT_PP_WHILE_5_0(p, op, st))
#define DESALT_PP_WHILE_5_1_I(p, op, st) DESALT_PP_WHILE_5_1_II(p, op, st)
#define DESALT_PP_WHILE_5_1_II(p, op, st) BOOST_PP_IF(p(4, st), DESALT_PP_WHILE_5_0, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_5_0(p, op, st) op(4, st)

#define DESALT_PP_WHILE_6(p, op, st) DESALT_PP_WHILE_6_I(p, BOOST_PP_IF(p(5, st), DESALT_PP_WHILE_6_15, st BOOST_PP_TUPLE_EAT(3))(p, op, st))
#define DESALT_PP_WHILE_6_I(p, st) BOOST_PP_IF(p(5, st), DESALT_PP_ERROR_WHILE_LOOP_OVER, st)

#define DESALT_PP_WHILE_6_15(p, op, st) DESALT_PP_WHILE_6_15_I(p, op, DESALT_PP_WHILE_6_14(p, op, st))
#define DESALT_PP_WHILE_6_15_I(p, op, st) DESALT_PP_WHILE_6_15_II(p, op, st)
#define DESALT_PP_WHILE_6_15_II(p, op, st) BOOST_PP_IF(p(5, st), DESALT_PP_WHILE_6_14, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_6_14(p, op, st) DESALT_PP_WHILE_6_14_I(p, op, DESALT_PP_WHILE_6_13(p, op, st))
#define DESALT_PP_WHILE_6_14_I(p, op, st) DESALT_PP_WHILE_6_14_II(p, op, st)
#define DESALT_PP_WHILE_6_14_II(p, op, st) BOOST_PP_IF(p(5, st), DESALT_PP_WHILE_6_13, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_6_13(p, op, st) DESALT_PP_WHILE_6_13_I(p, op, DESALT_PP_WHILE_6_12(p, op, st))
#define DESALT_PP_WHILE_6_13_I(p, op, st) DESALT_PP_WHILE_6_13_II(p, op, st)
#define DESALT_PP_WHILE_6_13_II(p, op, st) BOOST_PP_IF(p(5, st), DESALT_PP_WHILE_6_12, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_6_12(p, op, st) DESALT_PP_WHILE_6_12_I(p, op, DESALT_PP_WHILE_6_11(p, op, st))
#define DESALT_PP_WHILE_6_12_I(p, op, st) DESALT_PP_WHILE_6_12_II(p, op, st)
#define DESALT_PP_WHILE_6_12_II(p, op, st) BOOST_PP_IF(p(5, st), DESALT_PP_WHILE_6_11, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_6_11(p, op, st) DESALT_PP_WHILE_6_11_I(p, op, DESALT_PP_WHILE_6_10(p, op, st))
#define DESALT_PP_WHILE_6_11_I(p, op, st) DESALT_PP_WHILE_6_11_II(p, op, st)
#define DESALT_PP_WHILE_6_11_II(p, op, st) BOOST_PP_IF(p(5, st), DESALT_PP_WHILE_6_10, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_6_10(p, op, st) DESALT_PP_WHILE_6_10_I(p, op, DESALT_PP_WHILE_6_9(p, op, st))
#define DESALT_PP_WHILE_6_10_I(p, op, st) DESALT_PP_WHILE_6_10_II(p, op, st)
#define DESALT_PP_WHILE_6_10_II(p, op, st) BOOST_PP_IF(p(5, st), DESALT_PP_WHILE_6_9, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_6_9(p, op, st) DESALT_PP_WHILE_6_9_I(p, op, DESALT_PP_WHILE_6_8(p, op, st))
#define DESALT_PP_WHILE_6_9_I(p, op, st) DESALT_PP_WHILE_6_9_II(p, op, st)
#define DESALT_PP_WHILE_6_9_II(p, op, st) BOOST_PP_IF(p(5, st), DESALT_PP_WHILE_6_8, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_6_8(p, op, st) DESALT_PP_WHILE_6_8_I(p, op, DESALT_PP_WHILE_6_7(p, op, st))
#define DESALT_PP_WHILE_6_8_I(p, op, st) DESALT_PP_WHILE_6_8_II(p, op, st)
#define DESALT_PP_WHILE_6_8_II(p, op, st) BOOST_PP_IF(p(5, st), DESALT_PP_WHILE_6_7, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_6_7(p, op, st) DESALT_PP_WHILE_6_7_I(p, op, DESALT_PP_WHILE_6_6(p, op, st))
#define DESALT_PP_WHILE_6_7_I(p, op, st) DESALT_PP_WHILE_6_7_II(p, op, st)
#define DESALT_PP_WHILE_6_7_II(p, op, st) BOOST_PP_IF(p(5, st), DESALT_PP_WHILE_6_6, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_6_6(p, op, st) DESALT_PP_WHILE_6_6_I(p, op, DESALT_PP_WHILE_6_5(p, op, st))
#define DESALT_PP_WHILE_6_6_I(p, op, st) DESALT_PP_WHILE_6_6_II(p, op, st)
#define DESALT_PP_WHILE_6_6_II(p, op, st) BOOST_PP_IF(p(5, st), DESALT_PP_WHILE_6_5, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_6_5(p, op, st) DESALT_PP_WHILE_6_5_I(p, op, DESALT_PP_WHILE_6_4(p, op, st))
#define DESALT_PP_WHILE_6_5_I(p, op, st) DESALT_PP_WHILE_6_5_II(p, op, st)
#define DESALT_PP_WHILE_6_5_II(p, op, st) BOOST_PP_IF(p(5, st), DESALT_PP_WHILE_6_4, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_6_4(p, op, st) DESALT_PP_WHILE_6_4_I(p, op, DESALT_PP_WHILE_6_3(p, op, st))
#define DESALT_PP_WHILE_6_4_I(p, op, st) DESALT_PP_WHILE_6_4_II(p, op, st)
#define DESALT_PP_WHILE_6_4_II(p, op, st) BOOST_PP_IF(p(5, st), DESALT_PP_WHILE_6_3, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_6_3(p, op, st) DESALT_PP_WHILE_6_3_I(p, op, DESALT_PP_WHILE_6_2(p, op, st))
#define DESALT_PP_WHILE_6_3_I(p, op, st) DESALT_PP_WHILE_6_3_II(p, op, st)
#define DESALT_PP_WHILE_6_3_II(p, op, st) BOOST_PP_IF(p(5, st), DESALT_PP_WHILE_6_2, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_6_2(p, op, st) DESALT_PP_WHILE_6_2_I(p, op, DESALT_PP_WHILE_6_1(p, op, st))
#define DESALT_PP_WHILE_6_2_I(p, op, st) DESALT_PP_WHILE_6_2_II(p, op, st)
#define DESALT_PP_WHILE_6_2_II(p, op, st) BOOST_PP_IF(p(5, st), DESALT_PP_WHILE_6_1, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_6_1(p, op, st) DESALT_PP_WHILE_6_1_I(p, op, DESALT_PP_WHILE_6_0(p, op, st))
#define DESALT_PP_WHILE_6_1_I(p, op, st) DESALT_PP_WHILE_6_1_II(p, op, st)
#define DESALT_PP_WHILE_6_1_II(p, op, st) BOOST_PP_IF(p(5, st), DESALT_PP_WHILE_6_0, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_6_0(p, op, st) op(5, st)

#define DESALT_PP_WHILE_7(p, op, st) DESALT_PP_WHILE_7_I(p, BOOST_PP_IF(p(6, st), DESALT_PP_WHILE_7_15, st BOOST_PP_TUPLE_EAT(3))(p, op, st))
#define DESALT_PP_WHILE_7_I(p, st) BOOST_PP_IF(p(6, st), DESALT_PP_ERROR_WHILE_LOOP_OVER, st)

#define DESALT_PP_WHILE_7_15(p, op, st) DESALT_PP_WHILE_7_15_I(p, op, DESALT_PP_WHILE_7_14(p, op, st))
#define DESALT_PP_WHILE_7_15_I(p, op, st) DESALT_PP_WHILE_7_15_II(p, op, st)
#define DESALT_PP_WHILE_7_15_II(p, op, st) BOOST_PP_IF(p(6, st), DESALT_PP_WHILE_7_14, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_7_14(p, op, st) DESALT_PP_WHILE_7_14_I(p, op, DESALT_PP_WHILE_7_13(p, op, st))
#define DESALT_PP_WHILE_7_14_I(p, op, st) DESALT_PP_WHILE_7_14_II(p, op, st)
#define DESALT_PP_WHILE_7_14_II(p, op, st) BOOST_PP_IF(p(6, st), DESALT_PP_WHILE_7_13, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_7_13(p, op, st) DESALT_PP_WHILE_7_13_I(p, op, DESALT_PP_WHILE_7_12(p, op, st))
#define DESALT_PP_WHILE_7_13_I(p, op, st) DESALT_PP_WHILE_7_13_II(p, op, st)
#define DESALT_PP_WHILE_7_13_II(p, op, st) BOOST_PP_IF(p(6, st), DESALT_PP_WHILE_7_12, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_7_12(p, op, st) DESALT_PP_WHILE_7_12_I(p, op, DESALT_PP_WHILE_7_11(p, op, st))
#define DESALT_PP_WHILE_7_12_I(p, op, st) DESALT_PP_WHILE_7_12_II(p, op, st)
#define DESALT_PP_WHILE_7_12_II(p, op, st) BOOST_PP_IF(p(6, st), DESALT_PP_WHILE_7_11, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_7_11(p, op, st) DESALT_PP_WHILE_7_11_I(p, op, DESALT_PP_WHILE_7_10(p, op, st))
#define DESALT_PP_WHILE_7_11_I(p, op, st) DESALT_PP_WHILE_7_11_II(p, op, st)
#define DESALT_PP_WHILE_7_11_II(p, op, st) BOOST_PP_IF(p(6, st), DESALT_PP_WHILE_7_10, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_7_10(p, op, st) DESALT_PP_WHILE_7_10_I(p, op, DESALT_PP_WHILE_7_9(p, op, st))
#define DESALT_PP_WHILE_7_10_I(p, op, st) DESALT_PP_WHILE_7_10_II(p, op, st)
#define DESALT_PP_WHILE_7_10_II(p, op, st) BOOST_PP_IF(p(6, st), DESALT_PP_WHILE_7_9, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_7_9(p, op, st) DESALT_PP_WHILE_7_9_I(p, op, DESALT_PP_WHILE_7_8(p, op, st))
#define DESALT_PP_WHILE_7_9_I(p, op, st) DESALT_PP_WHILE_7_9_II(p, op, st)
#define DESALT_PP_WHILE_7_9_II(p, op, st) BOOST_PP_IF(p(6, st), DESALT_PP_WHILE_7_8, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_7_8(p, op, st) DESALT_PP_WHILE_7_8_I(p, op, DESALT_PP_WHILE_7_7(p, op, st))
#define DESALT_PP_WHILE_7_8_I(p, op, st) DESALT_PP_WHILE_7_8_II(p, op, st)
#define DESALT_PP_WHILE_7_8_II(p, op, st) BOOST_PP_IF(p(6, st), DESALT_PP_WHILE_7_7, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_7_7(p, op, st) DESALT_PP_WHILE_7_7_I(p, op, DESALT_PP_WHILE_7_6(p, op, st))
#define DESALT_PP_WHILE_7_7_I(p, op, st) DESALT_PP_WHILE_7_7_II(p, op, st)
#define DESALT_PP_WHILE_7_7_II(p, op, st) BOOST_PP_IF(p(6, st), DESALT_PP_WHILE_7_6, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_7_6(p, op, st) DESALT_PP_WHILE_7_6_I(p, op, DESALT_PP_WHILE_7_5(p, op, st))
#define DESALT_PP_WHILE_7_6_I(p, op, st) DESALT_PP_WHILE_7_6_II(p, op, st)
#define DESALT_PP_WHILE_7_6_II(p, op, st) BOOST_PP_IF(p(6, st), DESALT_PP_WHILE_7_5, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_7_5(p, op, st) DESALT_PP_WHILE_7_5_I(p, op, DESALT_PP_WHILE_7_4(p, op, st))
#define DESALT_PP_WHILE_7_5_I(p, op, st) DESALT_PP_WHILE_7_5_II(p, op, st)
#define DESALT_PP_WHILE_7_5_II(p, op, st) BOOST_PP_IF(p(6, st), DESALT_PP_WHILE_7_4, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_7_4(p, op, st) DESALT_PP_WHILE_7_4_I(p, op, DESALT_PP_WHILE_7_3(p, op, st))
#define DESALT_PP_WHILE_7_4_I(p, op, st) DESALT_PP_WHILE_7_4_II(p, op, st)
#define DESALT_PP_WHILE_7_4_II(p, op, st) BOOST_PP_IF(p(6, st), DESALT_PP_WHILE_7_3, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_7_3(p, op, st) DESALT_PP_WHILE_7_3_I(p, op, DESALT_PP_WHILE_7_2(p, op, st))
#define DESALT_PP_WHILE_7_3_I(p, op, st) DESALT_PP_WHILE_7_3_II(p, op, st)
#define DESALT_PP_WHILE_7_3_II(p, op, st) BOOST_PP_IF(p(6, st), DESALT_PP_WHILE_7_2, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_7_2(p, op, st) DESALT_PP_WHILE_7_2_I(p, op, DESALT_PP_WHILE_7_1(p, op, st))
#define DESALT_PP_WHILE_7_2_I(p, op, st) DESALT_PP_WHILE_7_2_II(p, op, st)
#define DESALT_PP_WHILE_7_2_II(p, op, st) BOOST_PP_IF(p(6, st), DESALT_PP_WHILE_7_1, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_7_1(p, op, st) DESALT_PP_WHILE_7_1_I(p, op, DESALT_PP_WHILE_7_0(p, op, st))
#define DESALT_PP_WHILE_7_1_I(p, op, st) DESALT_PP_WHILE_7_1_II(p, op, st)
#define DESALT_PP_WHILE_7_1_II(p, op, st) BOOST_PP_IF(p(6, st), DESALT_PP_WHILE_7_0, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_7_0(p, op, st) op(6, st)

#define DESALT_PP_WHILE_8(p, op, st) DESALT_PP_WHILE_8_I(p, BOOST_PP_IF(P(7, st), DESALT_PP_WHILE_8_15, st BOOST_PP_TUPLE_EAT(3))(p, op, st))
#define DESALT_PP_WHILE_8_I(p, st) BOOST_PP_IF(P(7, st), DESALT_PP_ERROR_WHILE_LOOP_OVER, st)

#define DESALT_PP_WHILE_8_15(p, op, st) DESALT_PP_WHILE_8_15_I(p, op, DESALT_PP_WHILE_8_14(p, op, st))
#define DESALT_PP_WHILE_8_15_I(p, op, st) DESALT_PP_WHILE_8_15_II(p, op, st)
#define DESALT_PP_WHILE_8_15_II(p, op, st) BOOST_PP_IF(P(7, st), DESALT_PP_WHILE_8_14, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_8_14(p, op, st) DESALT_PP_WHILE_8_14_I(p, op, DESALT_PP_WHILE_8_13(p, op, st))
#define DESALT_PP_WHILE_8_14_I(p, op, st) DESALT_PP_WHILE_8_14_II(p, op, st)
#define DESALT_PP_WHILE_8_14_II(p, op, st) BOOST_PP_IF(P(7, st), DESALT_PP_WHILE_8_13, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_8_13(p, op, st) DESALT_PP_WHILE_8_13_I(p, op, DESALT_PP_WHILE_8_12(p, op, st))
#define DESALT_PP_WHILE_8_13_I(p, op, st) DESALT_PP_WHILE_8_13_II(p, op, st)
#define DESALT_PP_WHILE_8_13_II(p, op, st) BOOST_PP_IF(P(7, st), DESALT_PP_WHILE_8_12, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_8_12(p, op, st) DESALT_PP_WHILE_8_12_I(p, op, DESALT_PP_WHILE_8_11(p, op, st))
#define DESALT_PP_WHILE_8_12_I(p, op, st) DESALT_PP_WHILE_8_12_II(p, op, st)
#define DESALT_PP_WHILE_8_12_II(p, op, st) BOOST_PP_IF(P(7, st), DESALT_PP_WHILE_8_11, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_8_11(p, op, st) DESALT_PP_WHILE_8_11_I(p, op, DESALT_PP_WHILE_8_10(p, op, st))
#define DESALT_PP_WHILE_8_11_I(p, op, st) DESALT_PP_WHILE_8_11_II(p, op, st)
#define DESALT_PP_WHILE_8_11_II(p, op, st) BOOST_PP_IF(P(7, st), DESALT_PP_WHILE_8_10, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_8_10(p, op, st) DESALT_PP_WHILE_8_10_I(p, op, DESALT_PP_WHILE_8_9(p, op, st))
#define DESALT_PP_WHILE_8_10_I(p, op, st) DESALT_PP_WHILE_8_10_II(p, op, st)
#define DESALT_PP_WHILE_8_10_II(p, op, st) BOOST_PP_IF(P(7, st), DESALT_PP_WHILE_8_9, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_8_9(p, op, st) DESALT_PP_WHILE_8_9_I(p, op, DESALT_PP_WHILE_8_8(p, op, st))
#define DESALT_PP_WHILE_8_9_I(p, op, st) DESALT_PP_WHILE_8_9_II(p, op, st)
#define DESALT_PP_WHILE_8_9_II(p, op, st) BOOST_PP_IF(P(7, st), DESALT_PP_WHILE_8_8, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_8_8(p, op, st) DESALT_PP_WHILE_8_8_I(p, op, DESALT_PP_WHILE_8_7(p, op, st))
#define DESALT_PP_WHILE_8_8_I(p, op, st) DESALT_PP_WHILE_8_8_II(p, op, st)
#define DESALT_PP_WHILE_8_8_II(p, op, st) BOOST_PP_IF(P(7, st), DESALT_PP_WHILE_8_7, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_8_7(p, op, st) DESALT_PP_WHILE_8_7_I(p, op, DESALT_PP_WHILE_8_6(p, op, st))
#define DESALT_PP_WHILE_8_7_I(p, op, st) DESALT_PP_WHILE_8_7_II(p, op, st)
#define DESALT_PP_WHILE_8_7_II(p, op, st) BOOST_PP_IF(P(7, st), DESALT_PP_WHILE_8_6, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_8_6(p, op, st) DESALT_PP_WHILE_8_6_I(p, op, DESALT_PP_WHILE_8_5(p, op, st))
#define DESALT_PP_WHILE_8_6_I(p, op, st) DESALT_PP_WHILE_8_6_II(p, op, st)
#define DESALT_PP_WHILE_8_6_II(p, op, st) BOOST_PP_IF(P(7, st), DESALT_PP_WHILE_8_5, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_8_5(p, op, st) DESALT_PP_WHILE_8_5_I(p, op, DESALT_PP_WHILE_8_4(p, op, st))
#define DESALT_PP_WHILE_8_5_I(p, op, st) DESALT_PP_WHILE_8_5_II(p, op, st)
#define DESALT_PP_WHILE_8_5_II(p, op, st) BOOST_PP_IF(P(7, st), DESALT_PP_WHILE_8_4, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_8_4(p, op, st) DESALT_PP_WHILE_8_4_I(p, op, DESALT_PP_WHILE_8_3(p, op, st))
#define DESALT_PP_WHILE_8_4_I(p, op, st) DESALT_PP_WHILE_8_4_II(p, op, st)
#define DESALT_PP_WHILE_8_4_II(p, op, st) BOOST_PP_IF(P(7, st), DESALT_PP_WHILE_8_3, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_8_3(p, op, st) DESALT_PP_WHILE_8_3_I(p, op, DESALT_PP_WHILE_8_2(p, op, st))
#define DESALT_PP_WHILE_8_3_I(p, op, st) DESALT_PP_WHILE_8_3_II(p, op, st)
#define DESALT_PP_WHILE_8_3_II(p, op, st) BOOST_PP_IF(P(7, st), DESALT_PP_WHILE_8_2, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_8_2(p, op, st) DESALT_PP_WHILE_8_2_I(p, op, DESALT_PP_WHILE_8_1(p, op, st))
#define DESALT_PP_WHILE_8_2_I(p, op, st) DESALT_PP_WHILE_8_2_II(p, op, st)
#define DESALT_PP_WHILE_8_2_II(p, op, st) BOOST_PP_IF(P(7, st), DESALT_PP_WHILE_8_1, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_8_1(p, op, st) DESALT_PP_WHILE_8_1_I(p, op, DESALT_PP_WHILE_8_0(p, op, st))
#define DESALT_PP_WHILE_8_1_I(p, op, st) DESALT_PP_WHILE_8_1_II(p, op, st)
#define DESALT_PP_WHILE_8_1_II(p, op, st) BOOST_PP_IF(P(7, st), DESALT_PP_WHILE_8_0, st BOOST_PP_TUPLE_EAT(3))(p, op, st)
#define DESALT_PP_WHILE_8_0(p, op, st) oP(7, st)

#endif
